### ISSUE TITLE
Program freezes when searching for data for identical names in the family tree

### ISSUE THREAD

**Issue by Luke0328** [lafu9989/csci2275final#1]
First, I added "john" and "bohn" to the tree as parents with child "fohn". Then, I added "fohn" and "lohn" as parents to "john". Finally, when I called the "Find Ancestors" function with "john" the terminal froze. 
My "Print Tree" looked like this:
...
john + bohn: fohn
fohn + sohn: john
When the program froze, the output was stuck like this:
Enter person's name: john

**Comment by lafu9989** [comment]
Thanks for pointing this out! The problem should be resolved now.
